ShopSWE/Areas/Admin/Controllers/danhsachsanphamController.cs
using Dapper;
using ShopSWE.Models.Enity;
using ShopSWE.Models.ViewModels;
using ShopSWE.Service;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ShopSWE.Areas.Admin.Controllers
{
    public class danhsachsanphamController : BaseController
    {
        // GET: Admin/danhsachsanpham
        public SHOPSWEEntities db = new SHOPSWEEntities();
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult Pagging(int pageIndex = 1, int pageSize = 20)
        {
            SanphamViewModels model = new SanphamViewModels();
            int upper = (pageIndex - 1) * pageSize;
            var emps = db.Sanpham1.OrderBy(x => x.ID);
            model.sanphams = emps.Skip(upper).Take(pageSize).ToList();
            model.pageIndex = pageIndex;
            model.pageSize = pageSize;
            model.TotalRecord = emps.Count();
            decimal totalPage = (decimal)model.TotalRecord / model.pageSize;
            model.TotalPage = decimal.ToInt32(Math.Ceiling(totalPage));
            return PartialView(model);
        }
        [HttpPost]
        public JsonResult Add(Sanpham1 sanpham)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    //add vào db
                    db.Sanpham1.Add(sanpham);
                    db.SaveChanges();
                    return Json(new { StatusCode = 200 }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    //Tên input, lỗi
                    IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
                    return Json(new { StatusCode = 500, Message = allErrors.FirstOrDefault().ErrorMessage }, JsonRequestBehavior.AllowGet);
                }
            }
            catch
            {
                return Json(new { StatusCode = 505, Message = "Lỗi Thêm Mới" }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult Edit(int ID = 0)
        {
            Sanpham1 sanpham1 = db.Sanpham1.Find(ID);
            if (sanpham1 == null)
            {
                return HttpNotFound();
            }
            return View(sanpham1);
        }
        [HttpPost]
        public ActionResult Edit(Sanpham1 sanpham1)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sanpham1).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sanpham1);
        }
        [HttpPost]
        public JsonResult Delete(int ID)
        {
            bool result = false;
            var u = db.Sanpham1.Where(x => x.ID == ID).FirstOrDefault();
            if (u != null)
            {
                db.Sanpham1.Remove(u);
                db.SaveChanges();
                result = true;
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Detail(int ID)
        {
            Sanpham1 sanpham1 = db.Sanpham1.Find(ID);
            if (sanpham1 == null)
            {
                return HttpNotFound();
            }
            return View(sanpham1);
        }
        public ActionResult Donhang()
        {
            return View();
        }
        public PartialViewResult PaggingOrder(int pageIndex = 1, int pageSize = 20)
        {
            OrderViewModel model = new OrderViewModel();
            int upper = (pageIndex - 1) * pageSize;
            var emps = db.Order1.OrderBy(x => x.OrderID);
            model.orders = emps.Skip(upper).Take(pageSize).ToList();
            model.pageIndex = pageIndex;
            model.pageSize = pageSize;
            model.TotalRecord = emps.Count();
            decimal totalPage = (decimal)model.TotalRecord / model.pageSize;
            model.TotalPage = decimal.ToInt32(Math.Ceiling(totalPage));
            return PartialView(model);
        }
        public ActionResult DetailDonHang(int? OrderID)
        {
            if (OrderID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<OrderDetail> orderDetail = db.OrderDetails.Where(e => e.OrderID == OrderID).ToList();
            if (orderDetail == null)
            {
                return HttpNotFound();
            }
            return View(orderDetail);
        }
        public ActionResult SearchName(string Name)
        {
            try
            {
                if (string.IsNullOrEmpty(Name))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }                
                List<Order1> searchName = db.Order1.Where(e => e.ShipName.Contains(Name)).ToList();
                return View(searchName);
            }
            catch
            {
                return RedirectToAction("ActionDenied", "Common");
            }
        }
    }
}

ShopSWE/Areas/Admin/Views/danhsachsanpham/Detail.cshtml
@model ShopSWE.Models.Enity.Sanpham1
@{
    ViewBag.Title = "Detail";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Detail</h2>

    <tr>
        <td>@Model.Name</td>
        <td>@Model.Price</td>
        <td>@Model.Img</td>
        <td>@Model.Img2</td>
    </tr>

ShopSWE/Areas/Admin/Views/danhsachsanpham/DetailDonHang.cshtml
@model List<ShopSWE.Models.Enity.OrderDetail>
@using ShopSWE.Models.Enity
@{
    ViewBag.Title = "Detail";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";


    int? tongtien = 0;
    foreach (OrderDetail item in Model as List<OrderDetail>)
    {
        tongtien += item.Quantity * item.Price;
    }
}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="~/Content/Css/style.css">
<style>
    .admin {
        width: 50%;
        margin: 50px auto;
    }

        .admin h2 {
            position: relative;
            width: 50%;
            margin: 0 auto;
            font-weight: bold;
        }

    .admin-input {
        position: relative;
        width: 100%;
    }

        .admin-input p {
            font-weight: bold;
            font-size: 25px;
            margin: 10px 0;
        }

        .admin-input input {
            position: relative;
            width: 100%;
            height: 40px;
            border: 1px solid black;
            border-radius: 5px;
            outline: none;
            padding-left: 20px;
        }

    .admin button {
        position: relative;
        margin: 15px 0 0 15px;
        background-color: black;
        color: orange;
        font-weight: bold;
        border: none;
        padding: 7px 25px;
        border-radius: 5px;
        outline: none;
        transition: .4s all;
    }

        .admin button:hover {
            background-color: gray;
        }

    .table {
        text-align: center;
        margin-top: 15px;
        border-radius: 10px;
    }

        .table th {
            background: black;
            color: orange;
        }

    #table-engine, #table-engine1 {
        width: 90%;
        margin: 0 auto;
    }

    #Img {
        border: none;
    }

    #btnSelectImage, #btnSelectImage2 {
        width: 127px;
        font-size: 17px;
        background: black;
        color: orange;
        text-align: center;
        border-radius: 5px;
        padding-bottom: 2px;
        cursor: pointer;
    }

    .pagination {
        width: 170px;
        margin: 0 auto;
    }

        .pagination li {
            margin: 0 3px;
        }

    .page-link-active {
        background-color: orange;
        color: white;
        border: 2px solid orange;
    }

    .pagination a {
        color: black;
        font-weight: bold;
        padding: 6px 12px;
        border-radius: 100%;
        border: 2px solid black;
        transition: .3s all;
    }

        .pagination a:hover {
            background-color: orange;
            border: 2px solid black;
        }

    .page-item:last-child .page-link {
        border-top-right-radius: 100%;
        border-bottom-right-radius: 100%;
    }

    .page-item:first-child .page-link {
        border-top-left-radius: 100%;
        border-bottom-left-radius: 100%;
    }
</style>
<div id="table-engine">
    <h2>Sản Phẩm Order</h2>
    <table class="table table-hover text-nowrap">
        <thead>
            <tr>
                <th>Tên sản phẩm</th>
                <th>Số lượng</th>
                <th>Giá</th>
                <th>Tổng</th>
            </tr>
        </thead>
        <tbody>
            @foreach (OrderDetail item in Model as List<OrderDetail>)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Quantity</td>
                    <td>@(string.Format("{0:#,##0}", item.Price)) VNĐ</td>
                    <td>@(string.Format("{0:#,##0}", item.TotalPrice)) VNĐ</td>
                </tr>
            }
            <tr style="background: black; color:orange; font-weight:bold;">
                <td>Tổng Hóa Đơn</td>
                <td></td>
                <td></td>
                <td>@(string.Format("{0:#,##0}", tongtien)) VNĐ</td>
            </tr>
        </tbody>
    </table>
</div>

ShopSWE/Areas/Admin/Views/danhsachsanpham/Donhang.cshtml
@{
    ViewBag.Title = "Donhang";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<!-- Toasts -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css" rel="stylesheet" />
<link rel="stylesheet" href="~/Content/Css/style.css">
<style>
    .admin {
        width: 50%;
        margin: 50px auto;
    }

        .admin h2 {
            position: relative;
            width: 50%;
            margin: 0 auto;
            font-weight: bold;
        }

    .admin-input {
        position: relative;
        width: 100%;
    }

        .admin-input p {
            font-weight: bold;
            font-size: 25px;
            margin: 10px 0;
        }

        .admin-input input {
            position: relative;
            width: 100%;
            height: 40px;
            border: 1px solid black;
            border-radius: 5px;
            outline: none;
            padding-left: 20px;
        }

    .admin button {
        position: relative;
        margin: 15px 0 0 15px;
        background-color: black;
        color: orange;
        font-weight: bold;
        border: none;
        padding: 7px 25px;
        border-radius: 5px;
        outline: none;
        transition: .4s all;
    }

        .admin button:hover {
            background-color: gray;
        }

    .table {
        text-align: center;
        margin-top: 15px;
        border-radius: 10px;
    }

        .table th {
            background: black;
            color: orange;
        }

    #table-engine, #table-engine1 {
        width: 90%;
        margin: 0 auto;
    }

    #Img {
        border: none;
    }

    #btnSelectImage, #btnSelectImage2 {
        width: 127px;
        font-size: 17px;
        background: black;
        color: orange;
        text-align: center;
        border-radius: 5px;
        padding-bottom: 2px;
        cursor: pointer;
    }

    .pagination {
        width: 170px;
        margin: 0 auto;
    }

        .pagination li {
            margin: 0 3px;
        }

    .page-link-active {
        background-color: orange;
        color: white;
        border: 2px solid orange;
    }

    .pagination a {
        color: black;
        font-weight: bold;
        padding: 6px 12px;
        border-radius: 100%;
        border: 2px solid black;
        transition: .3s all;
    }

        .pagination a:hover {
            background-color: orange;
            border: 2px solid black;
        }

    .page-item:last-child .page-link {
        border-top-right-radius: 100%;
        border-bottom-right-radius: 100%;
    }

    .page-item:first-child .page-link {
        border-top-left-radius: 100%;
        border-bottom-left-radius: 100%;
    }
</style>
<div id="table-engine1" class="card-body table-responsive p-0">
    @{Html.RenderAction("PaggingOrder", "danhsachsanpham");}
</div>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script>
    function Refresh1(destination, pageIndex) {
        $.ajax({
            url: '/Admin/danhsachsanpham/PaggingOrder',
            type: 'GET',
            dataType: 'html',
            data: { pageIndex: pageIndex },
        })
            .done(function (res) {
                $(destination).html(res);
            })
            .fail(function () {

            })
            .always(function () {

            });
    }

</script>

ShopSWE/Areas/Admin/Views/danhsachsanpham/Edit.cshtml
@model ShopSWE.Models.Enity.Sanpham1

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="~/Content/Css/style.css">
<script src="~/Content/ckfinder/ckfinder.js"></script>

<style>
    .form-horizontal {
        width: 80%;
        margin: 0 auto;
    }

        .form-horizontal h3 {
            font-weight: bold;
            font-size: 25px;
            margin-left: 15px;
        }

        .form-horizontal h2 {
            font-weight: bold;
            font-size: 30px;
            margin: 10px 0 10px 15px;
        }

    .form-group button {
        border: none;
        background-color: black;
        color: orange;
        border-radius: 10px;
        padding: 6px 20px;
        font-weight: bold;
    }

    .form-group a {
        background-color: black;
        color: orange;
        border-radius: 10px;
        padding: 6px 20px;
        outline: none;
        font-weight: bold;
    }

        .form-group a:hover {
            text-decoration: none;
        }

    #btnSelectImage,#btnSelectImage2 {
        width: 127px;
        font-size: 17px;
        font-weight: bold;
        background: black;
        color: orange;
        text-align: center;
        border-radius: 5px;
        padding-bottom: 2px;
        cursor: pointer;
    }    
    .form-control{
        outline:none;
        border: 1px solid black;
    }
</style>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h2>Chỉnh sửa</h2>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)

    <div class="form-group">
        <h3>Tên Sản Phẩm</h3>
        @*@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @*@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })*@
        </div>
    </div>

    <div class="form-group">
        <h3>Giá Sản Phẩm</h3>
        @*@Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <h3>Ảnh Sản Phẩm</h3>
        @*@Html.LabelFor(model => model.Img, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="col-md-10">
            <p id="btnSelectImage">Chọn ảnh</p>
            @Html.EditorFor(model => model.Img, new { htmlAttributes = new { @class = "form-control", @id = "txtImage", @name = "Img" } })
            @Html.ValidationMessageFor(model => model.Img, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <h3>Ảnh Sản Phẩm</h3>
        @*@Html.LabelFor(model => model.Img2, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="col-md-10">
            <p id="btnSelectImage2">Chọn ảnh 2</p>
            @Html.EditorFor(model => model.Img2, new { htmlAttributes = new { @class = "form-control", @id = "txtImage2", @name = "Img2" } })
            @Html.ValidationMessageFor(model => model.Img2, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <h3>Ảnh Sản Phẩm</h3>
        @*@Html.LabelFor(model => model.Img2, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="col-md-10">
            <p id="btnSelectImage2">Chọn ảnh 2</p>
            @Html.EditorFor(model => model.Img2, new { htmlAttributes = new { @class = "form-control", @id = "txtImage2", @name = "Img2" } })
            @Html.ValidationMessageFor(model => model.Img2, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit">Save</button>
            <a href="@Url.Action("Index","danhsachsanpham")">Trở về Danh sách sản phẩm</a>
        </div>
    </div>
</div>
}

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script>
    $(document).ready(function () {
        $("#btnSelectImage").on('click', function () {
            var finder = new CKFinder();
            finder.selectActionFunction = function (url) {
                $('#txtImage').val(url);
            };
            finder.popup();
        })
        $("#btnSelectImage2").on('click', function () {
            var finder = new CKFinder();
            finder.selectActionFunction = function (url) {
                $('#txtImage2').val(url);
            };
            finder.popup();
        })
    })
</script>

ShopSWE/Areas/Admin/Views/danhsachsanpham/Index.cshtml
@model ShopSWE.Models.Enity.Sanpham1
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<!-- Toasts -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css" rel="stylesheet" />
<link rel="stylesheet" href="~/Content/Css/style.css">
<script src="~/Content/ckfinder/ckfinder.js"></script>
<style>
    .admin {
        width: 90%;
        margin: 50px auto;
    }

        .admin h2 {
            position: relative;
            width: 90%;
            margin: 0 auto;
            font-weight: bold;
            text-align: center;
        }

    .admin-input {
        position: relative;
        width: 100%;
    }

        .admin-input p {
            font-weight: bold;
            font-size: 25px;
            margin: 10px 0;
        }

        .admin-input input {
            position: relative;
            width: 100%;
            height: 40px;
            border: 1px solid black;
            border-radius: 5px;
            outline: none;
            padding-left: 20px;
        }

    .admin button {
        position: relative;
        margin: 15px 0 0 15px;
        background-color: black;
        color: orange;
        font-weight: bold;
        border: none;
        padding: 7px 25px;
        border-radius: 5px;
        outline: none;
        transition: .4s all;
    }

        .admin button:hover {
            background-color: gray;
        }

    .table {
        text-align: center;
        margin-top: 15px;
        border-radius: 10px;
    }

        .table th {
            background: black;
            color: orange;
        }

    #table-engine, #table-engine1 {
        width: 90%;
        margin: 0 auto;
    }

    #Img {
        border: none;
    }

    #btnSelectImage, #btnSelectImage2 {
        width: 127px;
        font-size: 17px;
        background: black;
        color: orange;
        text-align: center;
        border-radius: 5px;
        padding-bottom: 2px;
        cursor: pointer;
    }

    #radio {
        width: 20px;
        height: 20px;
        margin-left: 20px;
    }

    #span-select {
        font-weight: bold;
    }

    .pagination {
        width: 170px;
        margin: 0 auto;
    }

        .pagination li {
            margin: 0 3px;
        }

    .page-link-active {
        background-color: orange;
        color: white;
        border: 2px solid orange;
    }

    .pagination a {
        color: black;
        font-weight: bold;
        padding: 6px 12px;
        border-radius: 100%;
        border: 2px solid black;
        transition: .3s all;
    }

        .pagination a:hover {
            background-color: orange;
            border: 2px solid black;
        }

    .page-item:last-child .page-link {
        border-top-right-radius: 100%;
        border-bottom-right-radius: 100%;
    }

    .page-item:first-child .page-link {
        border-top-left-radius: 100%;
        border-bottom-left-radius: 100%;
    }
</style>

<div id="input-area" class="admin">
    <!-- /.card-header -->
    <!-- form start -->
    <h2>Sản phẩm New Arrivals</h2>
    <form id="danhsachsanpham-form" action="/" method="post">
        <div class="row">
            <div class="admin-input col-6">
                <p>Tên sản phẩm</p>
                <input type="text" id="Name" name="Name" placeholder="Tên sản phẩm">
            </div>
            <div class="admin-input col-6">
                <p>Giá sản phẩm</p>
                <input type="text" id="Price" name="Price" placeholder="Giá sản phẩm">
            </div>
        </div>
        <div class="row">
            <div class="admin-input col-6">
                <p>Chọn ảnh sản phẩm</p>
                <p id="btnSelectImage">Chọn ảnh</p>
                <input type="text" id="txtImage" name="Img">
            </div>
            <div class="admin-input col-6">
                <p>Chọn ảnh 2 của sản phẩm</p>
                <p id="btnSelectImage2">Chọn ảnh</p>
                <input type="text" id="txtImage2" name="Img2">
            </div>
        </div>
        <div class="row">
            <div class="admin-input col-12">
                <p>Date</p>
                <input type="text" value="@string.Format("{0:g}", DateTime.Now)" name="CreateDate">
            </div>
        </div>
        <div class="row">
            <div class="admin-input col-6">
                <p>BestSeller</p>
                <div class="row">
                    <div>
                        <input type="radio" id="radio" name="BestSeller" value="0" />
                        <span id="span-select">Có</span>
                    </div>
                    <div>
                        <input type="radio" id="radio" name="BestSeller" value="" />
                        <span id="span-select">Không</span>
                    </div>
                </div>
            </div>
            <div class="admin-input col-6">
                <p>Loại Sản Phẩm</p>
                <div class="row">
                    <div>
                        <input type="radio" id="radio" name="Category" value="0" checked />
                        <span id="span-select">Top</span>
                    </div>
                    <div>
                        <input style="margin-left:57px;" type="radio" id="radio" name="Category" value="1" />
                        <span id="span-select">Outerwear</span>
                    </div>
                </div>
                <div class="row">
                    <div>
                        <input type="radio" id="radio" name="Category" value="2" />
                        <span id="span-select">Bottoms</span>
                    </div>
                    <div>
                        <input type="radio" id="radio" name="Category" value="3" />
                        <span id="span-select">Accessories</span>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <!-- /.card-body -->
    <div>
        <button type="button" onclick="Add();">Xác nhận sản phảm</button>
    </div>
</div>
<div id="table-engine" class="card-body table-responsive p-0">
    @{Html.RenderAction("Pagging", "danhsachsanpham");}
</div>


<script src="~/Content/sweetalert2/sweetalert2.all.js"></script>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>

<script>
    $(document).ready(function () {
        $("#btnSelectImage").on('click', function () {
            var finder = new CKFinder();
            finder.selectActionFunction = function (url) {
                $('#txtImage').val(url);
            };
            finder.popup();
        })
        $("#btnSelectImage2").on('click', function () {
            var finder = new CKFinder();
            finder.selectActionFunction = function (url) {
                $('#txtImage2').val(url);
            };
            finder.popup();
        })
    })
</script>
<script>
    function Refresh(destination, pageIndex) {
        $.ajax({
            url: '/Admin/danhsachsanpham/Pagging',
            type: 'GET',
            dataType: 'html',
            data: { pageIndex: pageIndex },
        })
            .done(function (res) {
                $(destination).html(res);
            })
            .fail(function () {

            })
            .always(function () {

            });
    }
    function Add() {
        let data = $('#danhsachsanpham-form').serialize();
        console.log(data);
        $.ajax({
            url: '/Admin/danhsachsanpham/Add',
            type: 'POST',
            dataType: 'json',
            data: data,
        })
            .done(function (res) {
                if (res.StatusCode == 200) {
                    toastr.success('Thêm mới thành công!', 'Success !!!');
                    Refresh('#table-engine');
                }
                else {
                    toastr.error(res.Message, 'Error !!!');
                }
            })
            .fail(function () {
                console.log("error");
            })
            .always(function () {
                console.log("complete");
            });
    }

    function Delete(ID) {
        Swal.fire({
            title: 'Bạn có chắc chắn xóa không?',
            text: "Bạn sẽ không thể khôi phục lại được!",
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Xóa!!!'
        }).then((result) => {
            if (result.value) {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Delete")',
                    data: { ID: ID },
                    dataType: "json",
                    success: function () {
                        Refresh('#table-engine');
                        //setTimeout(function () {
                        //    location.href("/Admin/danhsachsanpham/Index").reload();
                        //}, 1000);
                    },
                    error: function () {
                        alert("Error while deleting data");
                    }
                });
            }
        })
    }


</script>